-- Create Companies Table
CREATE TABLE companies (
    company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(100),
    headquarters VARCHAR2(100),
    size VARCHAR2(100),
    founded NUMBER,
    type_of_ownership VARCHAR2(100),
    industry VARCHAR2(100),
    sector VARCHAR2(100),
    revenue VARCHAR2(100),
    competitors VARCHAR2(4000)
);

-- Create Locations Table
CREATE TABLE locations (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR2(100)
);

-- Create Jobs Table
CREATE TABLE jobs (
    job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR2(100),
    salary_estimate VARCHAR2(100),
    job_description CLOB,
    rating NUMBER(2, 1),
    company_id NUMBER,
    location_id NUMBER,
    FOREIGN KEY (company_id) REFERENCES companies(company_id),
    FOREIGN KEY (location_id) REFERENCES locations(location_id)
);
